[tool.black]
max-line-length = 100
target_version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git
    | \.virtualenv
    | __pycache__
    | test_content_version
  )/
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
#addopts = ""
