# Setup in CircleCI account the following ENV variables:
# PACKAGECLOUD_ORGANIZATION (default: stackstorm)
# PACKAGECLOUD_TOKEN
version: 2
jobs:
  # Run st2 Unit Tests
  unit:
    # 'machine' executor runs Unit tests ~x1.5 faster, comparing to 'docker' executor
    # but the fastest is still ~x1.5-2 slower, comparing to Travis
    machine: true
    parallelism: 3
    working_directory: ~/st2
    steps:
      - checkout
      - restore_cache:
          keys:
            - st2-unit-001-{{ checksum "fixed-requirements.txt" }}-{{ checksum "test-requirements.txt" }}
      - run:
          name: Prepare the environment
          command: |
            set -x
            sudo .circle/install-mongo.sh
            sudo .circle/configure-rabbitmq.sh
            sudo apt-get -qq -y install python-virtualenv python-dev
      - run:
          name: Create stanley user
          command: sudo .circle/add-itest-user.sh
      - run:
          name: Install pip requirements
          command: make requirements
      - run:
          name: Run st2 Unit Tests
          command: |
            # Workaround for table width/height used in some tests
            stty rows 50 cols 132
            make ci-unit
      - save_cache:
          key: st2-unit-001-{{ checksum "fixed-requirements.txt" }}-{{ checksum "test-requirements.txt" }}
          paths:
            - ~/.cache/pip/
            - virtualenv/

  # Run st2 Integration tests
  integration:
    docker:
      - image: circleci/python:3.8
      - image: mongo:4.4
      - image: rabbitmq:3
    working_directory: ~/st2
    steps:
      - checkout
      - restore_cache:
          keys:
            - st2-integration-001-{{ checksum "fixed-requirements.txt" }}-{{ checksum "test-requirements.txt" }}
      - run:
          # Download the mongo shell, needed to connect to Docker container + delete the DB
          name: Install Mongo Shell
          command: |
            set -x
            sudo apt-get -qq -y install gnupg curl
            curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/mongodb-server-4.4.gpg
            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
            sudo apt-get -qq -y update
            sudo apt-get -qq -y install mongodb-org-shell
      - run:
          name: Create stanley user
          command: sudo .circle/add-itest-user.sh
      - run:
          name: Install pip requirements
          command: make requirements
      - run:
          name: Run st2 Integration Tests
          command: make ci-integration
      - save_cache:
          key: st2-integration-001-{{ checksum "fixed-requirements.txt" }}-{{ checksum "test-requirements.txt" }}
          paths:
            - ~/.cache/pip/
            - virtualenv/

  # Run st2 Lint Checks
  lint:
    docker:
      - image: circleci/python:3.8
      - image: mongo:4.4
      - image: rabbitmq:3
    working_directory: ~/st2
    steps:
      - checkout
      - restore_cache:
          keys:
            # we can use the same caching env as for integration
            - st2-integration-001-{{ checksum "fixed-requirements.txt" }}-{{ checksum "test-requirements.txt" }}
      - run:
          name: Install pip requirements
          command: make requirements
      - run:
          name: Run st2 Lint Checks
          command: make ci-checks
      - run:
          name: Run st2 Packs Tests
          command: make ci-packs-tests
      - save_cache:
          # we can use the same caching env as for integration
          key: st2-integration-001-{{ checksum "fixed-requirements.txt" }}-{{ checksum "test-requirements.txt" }}
          paths:
            - ~/.cache/pip/
            - virtualenv/

  # Build & Test st2 packages
  packages:
    parallelism: 3
    # 4CPUs & 8GB RAM CircleCI machine
    # sadly, it doesn't work with 'setup_remote_docker'
    resource_class: large
    docker:
      # The primary container is an instance of the first list image listed. Your build commands run in this container.
      - image: circleci/python:3.8
    working_directory: ~/st2
    environment:
      - DISTROS: "focal el8 el9"
      - ST2_PACKAGES_REPO: https://github.com/StackStorm/st2-packages
      - ST2_PACKAGES: "st2"
      - ST2_CHECKOUT: 0
      - ST2_GITDIR: /tmp/st2
      - BASH_ENV: ~/.buildenv
    steps:
      - checkout
      - run:
          name: Install latest Docker Compose V2
          command: |
            set -x
            export CODENAME=$(source /etc/os-release && echo "$VERSION_CODENAME")
            export DISTRO=$(source /etc/os-release && echo "$ID")
            export ARCH=$(dpkg --print-architecture)
            # get gpg key for download.docker
            curl -fsSL https://download.docker.com/linux/${DISTRO}/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/download.docker.gpg
            # set source list
            sudo tee <<<"deb [arch=${ARCH}] https://download.docker.com/linux/${DISTRO} ${CODENAME} stable" /etc/apt/sources.list.d/download.docker.list
            # update package list
            sudo apt update
            # install docker CLI and Docker Compose v2
            sudo apt install docker-ce-cli docker-compose-plugin
      - setup_remote_docker:
          reusable: true    # default - false
          exclusive: true   # default - true
          version: docker24
      - run:
          name: Docker version
          command: |
            set -x
            docker --version
            docker compose version
      - run:
          name: Download st2-packages repository
          command: |
            set -x
            PIP_VERSION=$(grep ^PIP_VERSION Makefile)
            git clone ${ST2_PACKAGES_REPO} ~/st2-packages
            cd ~/st2-packages
            git checkout ${CIRCLE_BRANCH} || true
            sed -i -e "s/^PIP_VERSION .*$/${PIP_VERSION}/" packages/st2/debian/rules
      - run:
          name: Initialize packages Build Environment
          command: |
            set -x
            export ST2_GITREV=${CIRCLE_BRANCH}
            .circle/buildenv_st2.sh
          working_directory: ~/st2-packages
      # Verify that Docker environment is properly cleaned up and there is nothing left from the previous build
      # See issue: https://discuss.circleci.com/t/no-space-left-on-device-while-creating-mongo/11532/13
      - run:
          name: Pre Docker cleanup
          command: |
            set -x
            # Clean-up running containers
            .circle/docker-compose2.sh clean
            # Remove st2-packages-vol container
            docker rm -v --force st2-packages-vol || true
            # Clean-up any created volumes
            docker volume prune --force
          working_directory: ~/st2-packages
      - run:
          # Workaround for CircleCI docker-compose limitation where volumes don't work
          # See detailed explanation: https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
          name: Copy st2-packages files to build containers
          command: |
            # creating dummy container which will hold a volume with data files
            docker create -v /root/st2-packages -v ${ST2_GITDIR} -v /root/build -v /var/log/st2 -v /root/.cache/pip -v /tmp/wheelhouse --name st2-packages-vol alpine:3.12 /bin/true
            # copy st2-packages data files into this volume
            docker cp ~/st2-packages st2-packages-vol:/root
            # copy st2 source files into this volume
            docker cp . st2-packages-vol:${ST2_GITDIR}
      - run:
          name: Pull dependent Docker Images
          command: .circle/docker-compose2.sh pull ${DISTRO} || .circle/docker-compose2.sh pull ${DISTRO}
          working_directory: ~/st2-packages
      - run:
          name: Build the ${DISTRO} Packages
          command: |
            .circle/docker-compose2.sh build ${DISTRO}
            # Once build container finishes we can copy packages directly from it
            mkdir -p ~/st2/packages/${DISTRO}/log/
            docker cp st2-packages-vol:/root/build/. ~/st2/packages/${DISTRO}
          working_directory: ~/st2-packages
      - run:
          name: Test the Packages
          command: .circle/docker-compose2.sh test ${DISTRO}
          working_directory: ~/st2-packages
      - run:
          when: always
          name: Grab the st2 logs
          command: docker cp st2-packages-vol:/var/log/st2 ~/st2/packages/${DISTRO}/log/st2
      - store_artifacts:
          path: ~/st2/packages
          destination: packages
      - persist_to_workspace:
          root: packages
          paths:
            - .
      # Verify that Docker environment is properly cleaned up, and there is nothing left for the next build
      # See issue: https://discuss.circleci.com/t/no-space-left-on-device-while-creating-mongo/11532/13
      - run:
          name: Post Docker cleanup
          # don't cleanup resources on error since failed container might be used for SSH debug
          when: on_success
          command: |
            set -x
            # Clean-up running containers
            .circle/docker-compose2.sh clean
            # Remove st2-packages-vol container
            docker rm -v --force st2-packages-vol || true
            # Clean-up any created volumes
            docker volume prune --force
          working_directory: ~/st2-packages

  # Deploy produced deb/rpm packages to PackageCloud staging
  deploy:
    docker:
      # The primary container is an instance of the first list image listed. Your build commands run in this container.
      - image: circleci/ruby:2.7
    working_directory: /tmp/deploy
    environment:
      - DISTROS: "focal el8 el9"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: List workspace files
          command: find . | sed 's|[^/]*/|  |g'
      - run:
          name: Install dependencies
          command: |
            set -x
            sudo apt-get -y install parallel jq
            gem install package_cloud
            sudo wget -O /usr/local/bin/packagecloud.sh https://raw.githubusercontent.com/StackStorm/st2-packages/master/.circle/packagecloud.sh && sudo chmod +x /usr/local/bin/packagecloud.sh
      - run:
          name: Deploy deb/rpm packages to PackageCloud
          command: "parallel -v -j0 --line-buffer packagecloud.sh deploy {} {} ::: ${DISTROS}"

# TODO: Return to workflows when "Auto-cancel redundant buildsâ€ feature is implemented for Workflows: https://discuss.circleci.com/t/auto-cancel-redundant-builds-not-working-for-workflow/13852
# Putting everything together
workflows:
  version: 2
  package-test-and-deploy:
    jobs:
      - packages
      - deploy:
          requires:
            - packages
          filters:
            branches:
              only:
                - master
                - /v[0-9]+\.[0-9]+/
                - feature/circleci

experimental:
  notify:
    branches:
      only:
        - master
        - /v[0-9]+\.[0-9]+/

notify:
  webhooks:
    - url: https://ci-webhooks.stackstorm.com/webhooks/build/events
